version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
#      - /app/node_modules
      - ./:/app
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - "3000:3000"
      - "40273:40273"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: './nginx'
    ports:
      - '80:80'
    depends_on:
      - client