version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - WDS_SOCKET_PORT=0
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: './nginx'
    ports:
      - '80:80'
    depends_on:
      - client